#!/bin/bash

[ ${PI_ENV_LOADED} ] && return 0; readonly PI_ENV_LOADED=true

readonly PI_CONF_PACKAGE="sys-apps/ps3-gentoo-installer"
readonly PI_CONF_PACKAGE_NAME="ps3-gentoo-installer"
readonly PI_CONF_INSTALLER_SCRIPT_NAME="ps3-gentoo-installer"
readonly PI_CONF_CONFIG_NAME_SRC="PS3"
readonly PI_CONF_CONFIG_NAME_DST="config"
readonly PI_CONF_CONFIG_DIR_NAME="config"
readonly PI_CONF_DATA_DIR_NAME="data"

# Getting version of current and new ebuild.
readonly PI_PATH_OVERLAY_PACKAGE_DIR="${PATH_OVERLAYS_PS3_GENTOO}/${PI_CONF_PACKAGE}"
readonly PI_PATH_OVERLAY_DISTFILES_DIR="${PATH_OVERLAYS_PS3_GENTOO_DISTFILES}/${PI_CONF_PACKAGE}"
readonly PI_PATH_OVERLAY_EBUILD_CURRENT=$(find "${PI_PATH_OVERLAY_PACKAGE_DIR}" -name "${PI_CONF_PACKAGE_NAME}*.ebuild" | grep -v "9999" | sort -V | tail -n 1)
readonly PI_VAL_OVERLAY_EBUILD_CURRENT_VERSION="$(echo ${PI_PATH_OVERLAY_EBUILD_CURRENT} | sed -r 's/.*-([0-9]+(\.[0-9]+)*)\.ebuild/\1/')"
readonly PI_VAL_OVERLAY_EBUILD_NEW_VERSION=$(echo "${PI_VAL_OVERLAY_EBUILD_CURRENT_VERSION}" | awk -F. -v OFS=. '{ $NF=$NF+1; print }')

readonly PI_PATH_INSTALLER_SRC="${PATH_DEV_TOOLS_PS3_INSTALLER}/${PI_CONF_INSTALLER_SCRIPT_NAME}"
readonly PI_PATH_INSTALLER_DST="${PATH_WORK_PS3_INSTALLER}/${PI_CONF_INSTALLER_SCRIPT_NAME}"
readonly PI_PATH_CONFIG_SRC="${PATH_DEV_TOOLS_PS3_INSTALLER}/${PI_CONF_DATA_DIR_NAME}/${PI_CONF_CONFIG_DIR_NAME}/${PI_CONF_CONFIG_NAME_SRC}"
readonly PI_PATH_CONFIG_DST="${PATH_WORK_PS3_INSTALLER}/${PI_CONF_CONFIG_NAME_DST}"
readonly PI_PATH_EBUILD_SRC="${PATH_DEV_TOOLS_PS3_INSTALLER}/${PI_CONF_DATA_DIR_NAME}/${PI_CONF_PACKAGE_NAME}.ebuild"
readonly PI_PATH_EBUILD_DST="${PATH_WORK_PS3_INSTALLER}/${PI_CONF_PACKAGE_NAME}-${PI_VAL_OVERLAY_EBUILD_NEW_VERSION}.ebuild"
readonly PI_PATH_EBUILD_OVERLAY="${PI_PATH_OVERLAY_PACKAGE_DIR}/${PI_CONF_PACKAGE_NAME}-${PI_VAL_OVERLAY_EBUILD_NEW_VERSION}.ebuild"
readonly PI_PATH_DISTFILES_DST="${PATH_WORK_PS3_INSTALLER}/${PI_CONF_PACKAGE_NAME}-${PI_VAL_OVERLAY_EBUILD_NEW_VERSION}.tar.xz"
readonly PI_PATH_DISTFILES_OVERLAY="${PI_PATH_OVERLAY_DISTFILES_DIR}/${PI_CONF_PACKAGE_NAME}-${PI_VAL_OVERLAY_EBUILD_NEW_VERSION}.tar.xz"

readonly PI_CONF_LIST_DISTFILES_TAR_FILES=(
    "${PI_CONF_INSTALLER_SCRIPT_NAME}"
    "${PI_CONF_CONFIG_NAME_DST}"
)

ps3_installer_needs_update() {
    PI_VAL_TIMESTAMP_OVERLAY_EBUILD=$(stat --format=%Y ${PI_PATH_OVERLAY_EBUILD_CURRENT})
    PI_VAL_TIMESTAMP_DEV_TOOLS_INSTALLER=$(stat --format=%Y ${PI_PATH_INSTALLER_SRC})
    PI_VAL_TIMESTAMP_DEV_TOOLS_CONFIG=$(stat --format=%Y ${PI_PATH_CONFIG_SRC})
    if [[ ${PI_VAL_TIMESTAMP_DEV_TOOLS_INSTALLER} -gt ${PI_VAL_TIMESTAMP_OVERLAY_EBUILD} ]] || [[ ${PI_VAL_TIMESTAMP_DEV_TOOLS_CONFIG} -gt ${PI_VAL_TIMESTAMP_OVERLAY_EBUILD} ]]; then
        echo true
    fi
}
