#!/bin/bash

[ ! ${PS3_ENV_BINHOST_LOADED} ] || return 0
readonly PS3_ENV_BINHOST_LOADED=true

readonly B_CONF_RELEASE_NAME="${CONF_CATALYST_RELEASE_NAME_DFAULT}"
readonly B_PATH_BIND_SRC="${PATH_BINHOSTS_PS3_GENTOO}/${CONF_RELEASE_NAME}"
readonly B_PATH_BIND_DST="${PATH_CATALYST_PACKAGES}/${CONF_RELEASE_NAME}"

#readonly PATH_BINHOST="${PATH_BINHOSTS_PS3_GENTOO}/${CONF_RELEASE_NAME}"
readonly PATH_BINHOST_METADATA="${PATH_BIND_SRC}/Packages"
