#!/bin/bash

# This script merges manifest generated by function 06, with ps3 overlay and uploads it,
# alongside new distfiles to github.

die() {
    echo "$*" 1>&2
    exit 1
}

PACKAGE_VERSION="$1"

readonly PATH_START=$(dirname "$(realpath "$0")") || die "Failed to determine script directory."
readonly PATH_ROOT=$(realpath -m "${PATH_START}/../..") || die "Failed to determine root directory."
readonly PATH_VERSION_SCRIPT="${PATH_START}/ebuild-00-find-version.sh"
[ ! -z "${PACKAGE_VERSION}" ] || PACKAGE_VERSION=$($PATH_VERSION_SCRIPT) || die "Failed to get default version of package"
readonly NAME_EBUILD_FILE="gentoo-kernel-ps3-${PACKAGE_VERSION}.ebuild"
readonly NAME_DISTFILES_FILE="gentoo-kernel-ps3-files-${PACKAGE_VERSION}.tar.xz"
readonly NAME_DISTFILES_DIST_ENTRY="DIST ${NAME_DISTFILES_FILE}"
readonly PATH_WORK="/var/tmp/ps3/gentoo-kernel-ps3/${PACKAGE_VERSION}/ebuild"
readonly PATH_WORK_DISTFILES="${PATH_WORK}/distfiles"
readonly PATH_WORK_DISTFILES_TAR="${PATH_WORK_DISTFILES}/${NAME_DISTFILES_FILE}"
readonly PATH_WORK_EBUILD_FILE="${PATH_WORK}/sys-kernel/gentoo-kernel-ps3/${NAME_EBUILD_FILE}"
readonly PATH_EBUILD_MANIFEST="${PATH_WORK}/sys-kernel/gentoo-kernel-ps3/Manifest"
readonly PATH_OVERLAY_MAIN="${PATH_ROOT}/overlays/ps3-gentoo-overlay"
readonly PATH_OVERLAY_EBUILDS="${PATH_OVERLAY_MAIN}"
readonly PATH_OVERLAY_DISTFILES="${PATH_OVERLAY_MAIN}.distfiles"
readonly PATH_OVERLAY_MANIFEST="${PATH_OVERLAY_EBUILDS}/sys-kernel/gentoo-kernel-ps3/Manifest"
readonly PATHS_REPOSITORIES_TO_UPLOAD=(
    "${PATH_OVERLAY_DISTFILES}"
    "${PATH_OVERLAY_EBUILDS}"
)

# Verify data.
[[ "${PACKAGE_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+([0-9]+)?$ ]] || die "Please provide valid version number, ie. $0 6.6.30"
[ -d "${PATH_WORK}" ] || die "Workdir for version ${PACKAGE_VERSION} not found."
[ -f "${PATH_WORK_EBUILD_FILE}" ] || die "Ebuild for version ${PACKAGE_VERSION} not found."
[ -d "${PATH_WORK_DISTFILES}" ] || die "Distfiles for version ${PACKAGE_VERSION} not found."
[ -f "${PATH_EBUILD_MANIFEST}" ] || die "Manifest for version ${PACKAGE_VERSION} not found."

# Copy distfiles and ebuild
cp -rf "${PATH_WORK_DISTFILES}"/* "${PATH_OVERLAY_DISTFILES}/sys-kernel/gentoo-kernel-ps3"/ || die "Failed to copy distfiles"
cp -f "${PATH_WORK_EBUILD_FILE}" "${PATH_OVERLAY_EBUILDS}/sys-kernel/gentoo-kernel-ps3/${NAME_EBUILD_FILE}" || die "Failed to copy ebuild"

# Prune old manifest file from entries about ${NAME_DISTFILES_FILE} and add new entry
sed -i "/${NAME_DISTFILES_DIST_ENTRY}/d" "${PATH_OVERLAY_MANIFEST}" || die "Failed to prune Manifest from old entries"
cat "${PATH_EBUILD_MANIFEST}" >> "${PATH_OVERLAY_MANIFEST}" || die "Failed to add new entry to Manifest"

# Upload changes in repositories
for PATH_REPO in "${PATHS_REPOSITORIES_TO_UPLOAD[@]}"; do
    cd "${PATH_REPO}" || die "Failed to open ${PATH_REPO}"
    if [ -n "$(git status --porcelain)" ]; then
        git add -A || die "Failed to add files to repo ${PATH_REPO}"
        git commit -m "Gentoo-Kernel-PS3 package update" || die "Failed to commit files to repo ${PATH_REPO}"
        git push || die "Failed to push files to repo ${PATH_REPO}"
    else
        echo "No changes in repository ${PATH_REPO}. Skipping."
    fi
done

echo "Gentoo-Kernel-PS3 package ${PACKAGE_VERSION} merged successfully."
exit 0
